drop table if exists superheroes CASCADE;

create table superheroes (
       id bigint generated by default as identity,
       name varchar(15),
       first_name varchar(25),
       last_name varchar(25),
       primary key (id)
    );